substitutions:
  _GOSOMA_VERSION: 0.0.1
steps:
  - id: "Fazendo os testes unitários"
    name: gcr.io/cloud-builders/go
    args: ["test"]
    env: ["GOPATH=./src/soma/main"]
  - id: "Compilando"
    name: gcr.io/cloud-builders/go
    args: ["build"]
    env: ["GOPATH=./src/soma/main"]
  - id: "Gerando o container"
    name: gcr.io/cloud-builders/docker
    args: ["build","-t","gcr.io/codeeducation-hirao/gosoma:${_GOSOMA_VERSION}","-t","gcr.io/codeeducation-hirao/gosoma:latest","src/soma/"]
images:
  - 'gcr.io/$PROJECT_ID/gosoma:latest'
  - 'gcr.io/$PROJECT_ID/gosoma:${_GOSOMA_VERSION}'